### ISSUE TITLE
Typescript Error TS2304: Cannot find name 'ReadonlySet' / 'ReadonlyMap'

### ISSUE THREAD

**Issue by itstheeffi** [kolodny/immutability-helper#97] opened 2018-02-20 17:20 UTC
Hi,

I'm using Immutability-helper with a sample of SharePoint Webparts (it's called react-collapsible-textboxio).
Since a few days everytime I start my Webpart I get the Errors:

_[18:11:22] Error - typescript - node_modules\immutability-helper\index.d.ts(12,8): error TS2304: Cannot find name 'ReadonlySet'.
[18:11:22] Error - typescript - node_modules\immutability-helper\index.d.ts(14,3): error TS2304: Cannot find name 'ReadonlySet'.
[18:11:22] Error - typescript - node_modules\immutability-helper\index.d.ts(17,8): error TS2304: Cannot find name 'ReadonlyMap'.
[18:11:22] Error - typescript - node_modules\immutability-helper\index.d.ts(19,3): error TS2304: Cannot find name 'ReadonlyMap'._

I don't thinks the error is in the webpart itself, because Typescript links directly to the node_module a detects the error in there.
I can not say how this error appeared, it was just there I think as I reinstalled npm cause of a sync problem with git-repository...

I hope someone here can help me with my problem and thats the bes place to post it.

Thank you for your answers,
 - Effi

**Comment by andreiglingeanu** [comment] 2018-02-22 15:03
I think you need to use `lib: ['es6']`, as here: https://github.com/kolodny/immutability-helper/blob/master/tsconfig.json#L4

**Comment by itstheeffi** [comment] 2018-03-02 15:07
First of all thank you for your answer.
I noticed that I'm using "es5" right now, but my code doesn't look similar to yours.

{
  "compilerOptions": {
    "target": "es5",
    "forceConsistentCasingInFileNames": true,
    "module": "commonjs",
    "jsx": "react",
    "declaration": true,
    "sourceMap": true,
    "types": [
      "adal",
      "es6-promise",
      "es6-collections",
      "webpack-env"
    ]
  }
}

If I chage my target to es6 serveral more errors appear and my code still won't work.
Same thing if I use "lib: ['es6']".

**Comment by adelgado** [comment] 2018-05-05 03:24
It seems that in certain situations the typings infer Readonlyfied versions of some data structures. I've been able to route around this error by typing `update` explicitly. 

```ts
// ApplicationState['fruits'] is an Array<Fruit>

// [ts]
// Type 'ReadonlyArray<Fruit>' is not assignable to type 'Fruit[]'.
// Property 'push' is missing in type 'ReadonlyArray<Fruit>'.
return update(state, {
  $set: action.payload || initialState.fruits
})

// No errors:
return update<ApplicationState['fruits']>(state, {
  $set: action.payload || initialState.fruits
})
```

**Comment by Razinsky** [comment] 2018-05-25 14:04
I'm having the same problem here.. prioritizing this definition helps:
```
declare function update<T>(data: T, query: Query<T>): T
```
I really don't understand why to enforce `ReadonlyArray | ReadonlySet | ReadonlyMap` ? I know that those are and should always be read only values but it messes with our typings.

Using latest Typescript 2.8.3.

**Comment by kolodny** [comment] 2018-09-14 16:54
Is this still an issue?

**Comment by kolodny** [comment] 2018-09-16 19:07
Closing for now, feel free to reopen if this is still an issue

**Comment by daiict218** [comment] 2018-11-05 12:31
I'm facing this issue and can't get it working

**Comment by mwangaben** [comment] 2020-04-08 04:40
I was facing the same issue and i have resolved by set lib to es6 and dom like  below
`"target": "es5", 
"module": "commonjs",
"lib": ["es6", "dom"]",`

Hope this will fix the issue

**Comment by JakeThurman** [comment] 2020-04-28 12:48
Am running int this still. We can't include `es6` in our package since we have to support IE11.

**Comment by JakeThurman** [comment] 2020-04-28 15:20
To anyone else in my situation, (`es5` typescript target) here was our solution:

In an internal `.d.ts` file we include with [`typeRoots`](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types):

```ts
// TODO: Remove these when once we drop IE11 (and thus change our target to ES6)
//  These are needed to workaround various ES6 module typings and the ES5 "compatibility" in lodash's typings.
interface Map<K, V> { __never: never }
type ReadonlyMap<K, V> = never
interface Set<T> { __never: never }
type ReadonlySet<T> = never
```

Specifically the `__never: never` hack was needed because lodash includes the following in their typings:
```ts
interface Map<K, V> { }
interface Set<T> { }
```

Which means the typings for immutability-helper matched every `Spec<T extends object>` as `Spec<T extends Map<>>` since every object matches this interface with no properties. _What a mess!_

**Comment by kolodny** [comment] 2020-04-28 16:03
Reopening for now, I don't have the bandwidth to take this on but open to PRs to fix this

**Comment by DilanRamirez** [comment] 2020-06-25 19:34
> I was facing the same issue and i have resolved by set lib to es6 and dom like below
> `"target": "es5", "module": "commonjs", "lib": ["es6", "dom"]",`
> 
> Hope this will fix the issue

worked for me!

**Comment by gerardolima** [comment] 2020-11-17 15:17
I solved using the compiler flag `--lib ES6` (property "lib" on tsconfig.json)

**Comment by kolodny** [comment] 2021-12-19 03:31
Closing since there seems to be a (tsconfig) solution here

**Closed as completed by kolodny** 2021-12-19 03:31 UTC

**Comment by JakeThurman** [comment] 2021-12-19 13:14
While that's true, it's targeting es6 vs targeting es5. Which means losing support for Internet Explorer. which is likely acceptable. 

Also, the issue is really with lodash shipping global types named Map<> and Set<>, not with immutability helper.
