### ISSUE TITLE
Feature Request: Add path notation.

### ISSUE THREAD

**Issue by Parakleta** [kolodny/immutability-helper#64] opened 2017-10-03 09:29 UTC
Without a path notation it is not actually possible to edit an update spec object with an update spec since it cannot distinguish a key from an operation.  Adding path notation also has the advantage that it would also provide dot notation as requested in #17.

The method to disambiguate unusual keys is to use the normal bracket notation (with escaping for at least the close bracket) optionally with quote support.  With this the operation doesn’t actually need any special handling since it must always be the last element in any path.

This then gives the following:
```js
const newData = updatePath(myData, {
  "x.y.z.$set": 7,
  "a.b.$push": [9]
});
const newCollection = updatePath(collection, { "2.a.$splice": [[1, 1, 13, 14]]});
const newPathed = updatePath(pathed, {
  "[path.with.dots][next.part].$set": true, // sets pathed["path.with.dots"]["next.part"]
  "$set.$merge.$push": [1], // pushes to pathed.$set.$merge
  "[bracket\\]prop].$set": "eugh escapes", // sets pathed["bracket]prop"]
});
```

As an extension if double quotes are allowed in the brackets then automatic escaping of strings can be managed through `JSON.stringify()`.  Consider:
```js
const newData = updatePath(myData, {
  [`[${JSON.stringify(computedName)}].$set`]: "supports primitive values",
});
```

**Comment by hoytech** [comment] 2017-10-03 14:52
Thanks for the suggestion. I have implemented an `updatePath` function in my update-immutable package as of version 1.3.2 (on npm now). You can read its documentation (with some examples) here:

https://www.npmjs.com/package/update-immutable#updatepath

A few thoughts:

* If we are making a new interface, why have the operation be part of the path at all? I think it's cleaner to have it as a separate parameter so that is what I've implemented. In this case there is no need for the `$` prefix either.
* Computed paths are supported by passing in arrays instead of strings.
* The `updatePath` I have implemented may be less efficient than `update`. Besides the obvious overhead of parsing path strings, making multiple updates in a row with `updatePath` will require multiple recursive traversals of the structure (and multiple shallow copies), whereas a single `update` with multiple commands embedded can amortise this overhead over one call.
* Your suggestion of having the paths as keys of the update object theoretically could improve efficiency (see previous point) except that it would involve some mildly complicated recursive logic to merge the keys.
* Since the order updates are applied may be important, I prefer not to use object keys to represent this order as in your suggestion. I'm aware that most JS implementations preserve object insertion order (and that this is required by ES6), but semantically if order is important then I feel an array should be used. Your suggestion also has the limitation that you can't use the same path twice in one update. I decided to punt on this issue for now and not support multiple paths in one `updatePath` call.

**Comment by Parakleta** [comment] 2017-10-03 15:08
That was quick.  However, encoding everything in the string so that multiple operations could be specified was exactly the point.  Without this there is very little advantage over just using the lodash `set` function (with `clone` for immutability).

The order of updates should not matter any more than for the regular object specification method.  The only difference here is that it would be possible to specify conflicting or overlapping operations which couldn’t be specified in the object form, but this should be considered an error.

**Comment by hoytech** [comment] 2017-10-03 15:31
I'm not sure I follow. Each `updatePath` works like `update` so it only does shallow-copying of the structures necessary to apply the update (while preserving the original structure).

If efficiency is exactly the point then why do you want to encode everything into multiple strings, which then must be parsed and recursively merged for each update operation? You should stick to the original interface.

**Comment by Parakleta** [comment] 2017-10-03 21:17
It’s not about efficiency so much as convenience.  Performance is not as important as ease of use, and performance can always be improved later.  Consider:

```js
function splitPath(pathString) {
  const arr = [];
  /someRegExp/.replace(pathString, match => arr.push(match));
  const [ op, ...path ] = arr;
  return [ op, path ];
}
function myUpdatePath(obj, spec) {
  return Object.key(spec).reduce((next, pathString) =>
    yourUpdatePath(next, ...splitPath(pathString), spec[pathstring]), obj);
}
```

The two places performance can be improved would be memoizing `splitPath` (lodash already does this) and integrating the `reduce` to minimise the number of intermediate objects created (this is the real challenge).

**Comment by hoytech** [comment] 2017-10-03 21:36
> It’s not about efficiency so much as convenience.

Agreed completely. If you are after efficiency then the original API is much better than any `updatePath` that parses strings at run-time (memoized or not). I've considered building a way to compile update structures into JS code (either at build-time or dynamically using `eval`) before, but this has always seemed overkill.

In terms of convenience, the `updatePath` I have implemented is, I feel, comparable to yours. Using your examples:

    let newPathed = updatePath(pathed, 'set', ['path.with.dots', 'next.part'], true);
    newPathed = updatePath(newPathed, 'push', '$set.$merge', [1]);
    newPathed = updatePath(newPathed, 'set', 'bracket]prop', 'eugh escapes');

Certainly convenience is subjective, but I would argue that this implementation is even more-so than yours since there is no need to worry about escaping: If you have keys containing `.` characters then use the array version.

Additionally, there is no need to worry about, as you put it, specifying conflicting or overlapping operations.

**Comment by hoytech** [comment] 2017-10-03 22:32
I should say that it's possible that the memoisation would effectively offset the parsing overhead (from all but the first run). The problem is reconstructing a hierarchical update (as I think you're referring to re: `reduce`). If efficiency is a concern, it's simplest just to represent your update hierarchically in which case the trivial recursive implementation is optimal at using the fewest number of shallow copies.

**Comment by kolodny** [comment] 2017-11-14 17:30
That seems out of scope to this library but you can use the [flatulence](https://github.com/mephju/flatulence) library with this to accomplish that

```js
const flatulence = require("flatulence")

const newData = updatePath(myData, flatulence.unflatten({
  "x.y.z.$set": 7,
  "a.b.$push": [9]
}));
```

**Closed as completed by kolodny** 2017-11-14 17:30 UTC
