### ISSUE TITLE
typescript give a error when use update.extend

### ISSUE THREAD

**Issue by mrdulin** [kolodny/immutability-helper#90] opened 2018-02-05 08:04 UTC
I define my own operator using `update.extend`:

```ts
update.extend<IBook[]>('$updateObjFieldFromArrayById', function handler(param, old: IBook[]): IBook[] {
  return old.map((book: IBook): IBook => {
    if (book.id === param.id) {
      return update(book, { $merge: { [param.key]: param.value } });
    }
    return book;
  });
});
```

when I use it, typescript give a type error: 

```ts
      case UPDATE_BOOK_SELLOUT_FIELD_V2:
        nState = update(state, {
          books: {
            $updateObjFieldFromArrayById: { id: action.payload.id, key: 'sellout', value: action.payload.sellout }
          }
        });
        return nState;
```

```text
[ts]
Argument of type '{ books: { $updateObjFieldFromArrayById: { id: number; key: string; value: boolean; }; }; }' is not assignable to parameter of type 'Query<IBookState>'.
  Type '{ books: { $updateObjFieldFromArrayById: { id: number; key: string; value: boolean; }; }; }' is not assignable to type '(old: IBookState) => any'.
    Type '{ books: { $updateObjFieldFromArrayById: { id: number; key: string; value: boolean; }; }; }' provides no match for the signature '(old: IBookState): any'.
```

I think I should extend `index.d.ts` type, but how ? thanks.

**Comment by andreiglingeanu** [comment] 2018-02-14 21:59
I believe the problem is in the `update.extend` call itself & I'm not able to reproduce it on my end.

Here's the snippet I've used (note the `../` in `import update from '../immutability-helper';`, I'm using a local version of the module):

```typescript
import update from '../immutability-helper';

type IBook = { name: string, id: string}

update.extend<IBook[]>('$updateObjFieldFromArrayById', function handler(param, old: IBook[]): IBook[] {
	return old.map((book: IBook): IBook => {
		if (book.id === param.id) {
			return update(book, { $merge: { [param.key]: param.value } });
		}
		return book;
	});
});
```

Can you try it again after we merge #94?

**Comment by kolodny** [comment] 2018-09-14 16:54
@mrdulin Is this still an issue in the latest version?

**Comment by kolodny** [comment] 2018-09-16 19:07
Closing for now, feel free to reopen if this is still an issue

**Closed as completed by kolodny** 2018-09-16 19:07 UTC
